name: watchflix
description: "A Flutter application for browsing movies and TV shows across multiple streaming platforms. Features include content discovery, detailed information about movies and TV shows, and a clean, feature-first architecture using BLoC pattern."
publish_to: 'none'
version: 0.1.0

environment:
  flutter: ^3.27.3
  sdk: ^3.6.1

dependencies:
  chopper: ^8.0.4
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.0
  json_annotation: ^4.9.0
  leancode_cubit_utils: ^0.3.2
  leancode_hooks: ^0.1.1
  logging: ^1.3.0
  mocktail: ^1.0.4
  provider: ^6.1.2
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.14
  chopper_generator: ^8.0.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.5
  json_serializable: ^6.9.3
  leancode_lint: ^15.0.0
  swagger_dart_code_generator: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
